let sugestoes = [
    'Napoleão Bonaparte',
    'Júlio César',
    'Pirâmides do Egito',
    'Alexandre o Grande',
    'Cleópatra',
    '10 fatos sobre Napoleão Bonaparte',
    '10 fatos sobre Júlio César',
    '10 fatos sobre Pirâmides do Egito',
    '10 fatos sobre Alexandre o Grande',
    '10 fatos sobre Cleópatra',
    'Top 10 fatos sobre Napoleão Bonaparte',
    'Top 10 fatos sobre Júlio César',
    'Top 10 fatos sobre Pirâmides do Egito',
    'Top 10 fatos sobre Alexandre o Grande',
    'Top 10 fatos sobre Cleópatra',
]

const redirecionamentos = {
    'Napoleão Bonaparte': 'post.html?top-10-fatos-sobre-napoleao-bonaparte',
    'Júlio César': 'post.html?top-10-fatos-sobre-julio-cesar',
    'Pirâmides do Egito': 'post.html?piramides-do-egito-top-10-fatos-interessantes',
    'Alexandre o Grande': 'post.html?top-10-fatos-sobre-alexandre-o-grande',
    'Cleópatra': 'post.html?cleopatra-10-fatos-fascinantes-sobre-a-rainha-do-nilo',
    '10 fatos sobre Napoleão Bonaparte': 'post.html?top-10-fatos-sobre-napoleao-bonaparte',
    '10 fatos sobre Júlio César': 'post.html?top-10-fatos-sobre-julio-cesar',
    '10 fatos sobre Pirâmides do Egito': 'post.html?piramides-do-egito-top-10-fatos-interessantes',
    '10 fatos sobre Alexandre o Grande': 'post.html?top-10-fatos-sobre-alexandre-o-grande',
    '10 fatos sobre Cleópatra': 'post.html?cleopatra-10-fatos-fascinantes-sobre-a-rainha-do-nilo',
    'Top 10 fatos sobre Napoleão Bonaparte': 'post.html?top-10-fatos-sobre-napoleao-bonaparte',
    'Top 10 fatos sobre Júlio César': 'post.html?top-10-fatos-sobre-julio-cesar',
    'Top 10 fatos sobre Pirâmides do Egito': 'post.html?piramides-do-egito-top-10-fatos-interessantes',
    'Top 10 fatos sobre Alexandre o Grande': 'post.html?top-10-fatos-sobre-alexandre-o-grande',
    'Top 10 fatos sobre Cleópatra': 'post.html?cleopatra-10-fatos-fascinantes-sobre-a-rainha-do-nilo'
};